// This file was autogenerated by calcdeps.py
goog.addDependency('dev/breeze.js', [], ['Breeze', 'Breeze.Engine', 'Breeze.Engine.Director', 'Breeze.Engine.Scene', 'Breeze.Engine.Sound', 'Breeze.Engine.SoundCache', 'Breeze.Engine.Sprite', 'Breeze.Engine.Texture', 'Breeze.Engine.TextureCache']);
goog.addDependency('dev/core/namespace.breeze.js', ['Breeze'], []);
goog.addDependency('dev/engine/class.director.js', ['Breeze.Engine.Director'], ['Breeze.Engine', 'goog.math.Vec2', 'goog.object']);
goog.addDependency('dev/engine/class.scene.js', ['Breeze.Engine.Scene'], ['Breeze.Engine']);
goog.addDependency('dev/engine/class.sound.js', ['Breeze.Engine.Sound'], ['Breeze.Engine', 'jQuery', 'jPlayer', 'Modernizr']);
goog.addDependency('dev/engine/class.soundcache.js', ['Breeze.Engine.SoundCache'], ['Breeze.Engine']);
goog.addDependency('dev/engine/class.sprite.js', ['Breeze.Engine.Sprite'], ['Breeze.Engine']);
goog.addDependency('dev/engine/class.texture.js', ['Breeze.Engine.Texture'], ['Breeze.Engine']);
goog.addDependency('dev/engine/class.texturecache.js', ['Breeze.Engine.TextureCache'], ['Breeze.Engine']);
goog.addDependency('dev/engine/namespace.engine.js', ['Breeze.Engine'], ['Breeze']);
goog.addDependency('dev/vendors/jquery-1.4.2.js', ['jQuery'], []);
goog.addDependency('dev/vendors/jquery.jplayer.js', ['jPlayer'], ['jQuery']);
goog.addDependency('dev/vendors/modernizr-1.1.js', ['Modernizr', 'Modernizr.audio', 'Modernizr.audio.ogg', 'Modernizr.audio.mp3'], []);
